pub struct Metadata {
    image_id: ImageId,
    processing_info: ProcessingInfo,
    location: Location,
    listing_id: ListingId,
    listing: Listing,
    extra_info: ExtraInfo,
    property_description: PropertyDescription,
    semantic_description: SemanticDescription,
    property_title: PropertyTitle,
    semantic_title: SemanticTitle,
    property_type: PropertyType,
    semantic_type: SemanticType,
    property_status: PropertyTags,
    semantic_status: SemanticStatus,
    property_id: PropertyId,
    semantic_id: SemanticId,
    agentic_info: AgenticInfo,
}
